//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 05:42:40 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://training.wipro.com/webservicessoap/objects", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.wipro.training.webservicessoap.objects;
